# Generated by Django 5.0.7 on 2024-07-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_incomes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeIncomesExpenditures',
            new_name='TypeIncomes',
        ),
        migrations.RenameField(
            model_name='typeincomes',
            old_name='income_or_expenditure',
            new_name='income_name',
        ),
    ]
