# Generated by Django 5.0.7 on 2024-07-21 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_rename_typeincomesexpenditures_typeincomes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExpenditures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'type_expenditures',
            },
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='expenditure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.typeexpenditures'),
        ),
    ]
