# Generated by Django 5.0.7 on 2024-07-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_typeexpenditures_alter_expenditures_expenditure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditures',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Wallet.accounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomes',
            name='account_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Wallet.accounts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='expenditure_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.typeexpenditures'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='income_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.typeincomes'),
        ),
    ]
